
package co.com.touresbalon.foundation.microservices.dto.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "SystemFault", targetNamespace = "http://touresbalon.com.co/model/lodging/schema/v1")
public class FaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SystemFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public FaultMsg(String message, SystemFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public FaultMsg(String message, SystemFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: co.com.touresbalon.foundation.microservices.dto.soap.SystemFault
     */
    public SystemFault getFaultInfo() {
        return faultInfo;
    }

}
