
package com.hilton.foundation.soap.infrastructure;

import com.hilton.foundation.dto.soap.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BookingPort", targetNamespace = "http://hilton.com/enterprise/booking/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookingPort {


    /**
     * 
     * @param body
     * @return
     *     returns com.hilton.foundation.dto.soap.ConsultAvailabilityResType
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "consultAvailabilityResponse", targetNamespace = "http://hilton.com/enterprise/booking/schema/v1", partName = "body")
    public ConsultAvailabilityResType consultAvailability(
        @WebParam(name = "consultAvailabilityRequest", targetNamespace = "http://hilton.com/enterprise/booking/schema/v1", partName = "body")
        ConsultAvailabilityReqType body)
        throws FaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.hilton.foundation.dto.soap.ConfirmRoomResType
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "confirmRoomResponse", targetNamespace = "http://hilton.com/enterprise/booking/schema/v1", partName = "body")
    public ConfirmRoomResType confirmRoom(
        @WebParam(name = "confirmRoomRequest", targetNamespace = "http://hilton.com/enterprise/booking/schema/v1", partName = "body")
        ConfirmRoomReqType body)
        throws FaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.hilton.foundation.dto.soap.CancelRoomResType
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "cancelRoomResponse", targetNamespace = "http://hilton.com/enterprise/booking/schema/v1", partName = "body")
    public CancelRoomResType cancelRoom(
        @WebParam(name = "cancelRoomRequest", targetNamespace = "http://hilton.com/enterprise/booking/schema/v1", partName = "body")
        CancelRoomReqType body)
        throws FaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns com.hilton.foundation.dto.soap.GetReservationResType
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "getReservationResponse", targetNamespace = "http://hilton.com/enterprise/booking/schema/v1", partName = "body")
    public GetReservationResType getReservation(
        @WebParam(name = "getReservationRequest", targetNamespace = "http://hilton.com/enterprise/booking/schema/v1", partName = "body")
        GetReservationReqType body)
        throws FaultMsg
    ;

}
