
package co.com.touresbalon.foundation.microservices.soap.infrastructure;

import co.com.touresbalon.foundation.microservices.dto.soap.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LodgingPort", targetNamespace = "http://touresbalon.com.co/task/lodging/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LodgingPort {


    /**
     * 
     * @param body
     * @return
     *     returns co.com.touresbalon.foundation.microservices.dto.soap.AvailabilityResType
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "availabilityResponse", targetNamespace = "http://touresbalon.com.co/task/lodging/schema/v1", partName = "body")
    public AvailabilityResType consultRoomsAvailability(
        @WebParam(name = "availabilityRequest", targetNamespace = "http://touresbalon.com.co/task/lodging/schema/v1", partName = "body")
        AvailabilityReqType body)
        throws FaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns co.com.touresbalon.foundation.microservices.dto.soap.DoReservationResType
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "doReservationResponse", targetNamespace = "http://touresbalon.com.co/task/lodging/schema/v1", partName = "body")
    public DoReservationResType doReservation(
        @WebParam(name = "doReservationRequest", targetNamespace = "http://touresbalon.com.co/task/lodging/schema/v1", partName = "body")
        DoReservationReqType body)
        throws FaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns co.com.touresbalon.foundation.microservices.dto.soap.ConfirmReservationResType
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "confirmReservationResponse", targetNamespace = "http://touresbalon.com.co/task/lodging/schema/v1", partName = "body")
    public ConfirmReservationResType confirmReservation(
        @WebParam(name = "confirmReservationRequest", targetNamespace = "http://touresbalon.com.co/task/lodging/schema/v1", partName = "body")
        ConfirmReservationReqType body)
        throws FaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns co.com.touresbalon.foundation.microservices.dto.soap.CancelReservationResType
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "cancelReservationResponse", targetNamespace = "http://touresbalon.com.co/task/lodging/schema/v1", partName = "body")
    public CancelReservationResType cancelReservation(
        @WebParam(name = "cancelReservationRequest", targetNamespace = "http://touresbalon.com.co/task/lodging/schema/v1", partName = "body")
        CancelReservationReqType body)
        throws FaultMsg
    ;

    /**
     * 
     * @param body
     * @return
     *     returns co.com.touresbalon.foundation.microservices.dto.soap.GetReservationResType
     * @throws FaultMsg
     */
    @WebMethod
    @WebResult(name = "getReservationResponse", targetNamespace = "http://touresbalon.com.co/task/lodging/schema/v1", partName = "body")
    public GetReservationResType getReservation(
        @WebParam(name = "getReservationRequest", targetNamespace = "http://touresbalon.com.co/task/lodging/schema/v1", partName = "body")
        GetReservationReqType body)
        throws FaultMsg
    ;

}
