
package com.hilton.foundation.soap;

import com.hilton.foundation.soap.infrastructure.BookingPort;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BookingService", targetNamespace = "http://hilton.com/enterprise/booking/v1", wsdlLocation = "file:///j01/workspace/idea_projects/TouresBalon-Enterprise/EIS-Module/HiltonBookingWS/src/main/webapp/WEB-INF/wsdl/HiltonBookingService.wsdl")
public class BookingService
    extends Service
{

    private final static URL BOOKINGSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(BookingService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = BookingService.class.getResource(".");
            url = new URL(baseUrl, "file:///j01/workspace/idea_projects/TouresBalon-Enterprise/EIS-Module/HiltonBookingWS/src/main/webapp/WEB-INF/wsdl/HiltonBookingService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:///j01/workspace/idea_projects/TouresBalon-Enterprise/EIS-Module/HiltonBookingWS/src/main/webapp/WEB-INF/wsdl/HiltonBookingService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BOOKINGSERVICE_WSDL_LOCATION = url;
    }

    public BookingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookingService() {
        super(BOOKINGSERVICE_WSDL_LOCATION, new QName("http://hilton.com/enterprise/booking/v1", "BookingService"));
    }

    /**
     * 
     * @return
     *     returns BookingPort
     */
    @WebEndpoint(name = "BookingPort")
    public BookingPort getBookingPort() {
        return super.getPort(new QName("http://hilton.com/enterprise/booking/v1", "BookingPort"), BookingPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookingPort
     */
    @WebEndpoint(name = "BookingPort")
    public BookingPort getBookingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hilton.com/enterprise/booking/v1", "BookingPort"), BookingPort.class, features);
    }

}
