import co.com.touresbalon.foundation.businessrules.model.OrderFact

dialect  "mvel"



/*--------------------------------------------------------------------
 * --------   REGLAS DE NEGOCIO PARA CLIENTES TIPO PLATINO   ----------
 *--------------------------------------------------------------------
 */



rule "platinum customers"
    when
    $p : OrderFact( userType == 'platinum')
    then
     System.out.println(" ********* order pass platinum customers **********");
    $p.setApproval(true);
end


/*--------------------------------------------------------------------
 * --------   REGLAS DE NEGOCIO PARA CLIENTES TIPO DORADO   ----------
 *--------------------------------------------------------------------
 */

rule "gold customers"
salience 10
    when
    $p : OrderFact( userType == 'gold')
    then
     System.out.println(" ********* order pass customer gold **********");
    $p.setApproval(true);
end

/*--------------------------------------------------------------------
 * --------   REGLAS DE NEGOCIO PARA CLIENTES TIPO DORADO MONTO MAYOR   ----------
 *--------------------------------------------------------------------
 */
rule "gold customer with greater amount"
salience 5
    when
    $p : OrderFact( userType == 'gold' &&  6000000 < orderAmount )
    then
     System.out.println(" ********* order pass customer gold with greater amount **********");
    $p.setApproval(false);
end


/*--------------------------------------------------------------------
 * --------   REGLAS DE NEGOCIO PARA CLIENTES TIPO PLATEADO----------
 *--------------------------------------------------------------------
 */

rule "silver customer"
    when
    $p : OrderFact( userType == 'silver')
    then
     System.out.println(" ********* order pass customer silver **********");
    $p.setApproval(false);
end